---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "workload"
  namespace: "sandbox"
spec:
  selector:
    matchLabels:
      app: "workload"
  replicas: 1
  template:
    metadata:
      labels:
        app: "workload"
    spec:
      containers:
      - name: "workload-container"
        image: "nginx"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: "workload-service"
  namespace: "sandbox"
  annotations:
    "beta.cloud.google.com/backend-config": '{"default": "workload-default"}'
    "cloud.google.com/neg": '{"ingress":true,"exposed_ports": {"80":{"name": ""}}}'
spec:
  type: "NodePort"
  selector:
    app: "workload"
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: "workload-service2"
  namespace: "sandbox"
spec:
  type: "LoadBalancer"
  selector:
    app: "workload"
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "workload-ingress"
  namespace: "sandbox"
  annotations:
    networking.gke.io/managed-certificates: "workload-cert"
  # static ip
spec:
  rules:
  - host: "test.gitlab.inno.wb.bforbank.com"
    http:
      paths:
      - path: "/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: "workload-service"
            port:
              number: 80