---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "nginx-config"
  namespace: "sandbox-ingress"
data:
  my-site.conf: |
    server {
      listen       80;
      server_name  alex.sonar.inno.wb.bforbank.com;

      location /foo {
        alias /usr/share/nginx/html/;
        index  index.html index.htm;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "workload"
  namespace: "sandbox-ingress"
spec:
  selector:
    matchLabels:
      app: "workload"
  replicas: 1
  template:
    metadata:
      labels:
        app: "workload"
    spec:
      containers:
      - name: "workload-container"
        image: "nginx"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/etc/nginx/conf.d/"
            name: "nginx-config-vol"
      volumes:
        - name: "nginx-config-vol"
          configMap:
            name: "nginx-config"
            items:
              - key: "my-site.conf"
                path: "my-site.conf"
          
---
apiVersion: v1
kind: Service
metadata:
  name: "workload-service"
  namespace: "sandbox-ingress"
spec:
  type: "NodePort"
  selector:
    app: "workload"
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations: 
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: "alex.sonar.inno.wb.bforbank.com"
    http:
      paths:
      - path: "/foo"
        pathType: Prefix
        backend:
          service:
            name: "workload-service"
            port:
              number: 80
