apiVersion: "v1"
kind: Pod
metadata:
  name: "kubectl-test"
spec:
  serviceAccountName: "internal-kubectl"
  containers:
    - name: "kubectl"
      image: "alpine/k8s:1.21.5"
      command: [ "/bin/sh" ]
      args: [ "-c", "while true; do echo hello; sleep 10;done" ]
